### ISSUE TITLE
is there any example to use upload manually from another controller ?

### ISSUE THREAD

**Issue by raditzlawliet** [zxbodya/yii2-gallery-manager#18]
I want try to find a way to Upload Image manually, any example ? let me explain the case:
- Toilet Model -> Model with behavior using GalleryBehavior (normal use)
- ToiletController -> of course this is the controller
- Manual Model -> Model of Manual (manual upload)
- ManualController -> Another Controller with manual upload image,
- ManualController::actionAccept() -> when accept, image from manual moved / upload to Toilet Model

My Target is, using ManualController can I submit a image to Toilet Model, Image file (full path) already provide from ManualController , 

    public function actionAccept($id)
    {
        $model = $this->findModel($id);
        $model->status = Manual::STATUS_ACCEPTED;

        $modelToilet = Toilet::findModel($model->id_toilet);
        $modelFile = new ManualFile();
        $modelFile->manual = $model;
        $imagePath = $modelFile->getFilePath(true);
        if(!is_null($modelToilet)){
            //TODO save image ke Toilet
            
            $model->save();
        }else{
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        return $this->redirect(['index']);
    }

in section <code>//TODO</code> how to upload image to <code>$modelToilet</code> ?

Thanks.

**Comment by zxbodya** [comment]
Just:

```PHP
$modelToilet
  ->getBehavior('galleryBehaior') // put here name of behaviour into which you want to add image
  ->addImage($imagePath);
```

**Comment by raditzlawliet** [comment]
is it possible to add name & description too ?

**Comment by zxbodya** [comment]
Yes:

```PHP
$image = $modelToilet
  ->getBehavior('galleryBehaior') // put here name of behaviour into which you want to add image
  ->addImage($imagePath);

$modelToilet
  ->getBehavior('galleryBehaior')
  ->updateImagesData([
       $image->id => [
          'name'=>'....',
          'description'=>'....',
       ],
     ]);
```

**Comment by raditzlawliet** [comment]
Great, it works perfect !

@zxbodya btw, is this module development still on ? or will it become stable-release ?

**Comment by zxbodya** [comment]
I think, it is already quite stable... 
At least, no plans about any breaking changes in nearest time.

Need to update readme with more documentation, and to add version tag for composer...
