### ISSUE TITLE
Further update

### ISSUE THREAD

**Issue by taskas** [zxbodya/yii2-gallery-manager#2]
Hello,
Thanks for making this extension. I am not very keen on working with git yet, so i'm writting here.
I made a fork: https://github.com/taskas/yii2-gallery-manager and also made more adaption for yii2 with improvements:
* Fixed behavior to work in yii2
* Propose to use alias for images Urls, so for example in yii2 advanced backend app config you can set:
```
    'aliases'=> [
        '@galleryManagerRoot'=>realpath(dirname(__FILE__).'/../../public/'),
        '@galleryManagerRootUrl'=>'/public/',
    ],
```
* Made lame but still bit more useful implementation of image generation (see GalleryPhoto::updateImages function), so my model's behavior config looks like:
```
    public function behaviors()
    {
        return [
            'gallery' => [
                'class' => GalleryBehavior::className(),
                'idAttribute' => 'gallery_id',
                'extension'=>'png',
                'versions'=>[
                    'medium' => [
                        'widen' => [800],
                    ]
                ]
            ],
        ];
    }
```
* Modified table `gallery` by adding this column: `directory varchar(64) NOT NULL`

Well, check my last commit. I sorta didn't know how to push to your repository. Still learning git stuff...
Hope it will help!

**Comment by zxbodya** [comment]
Just published updated version, check it out.

Now it was fully ported to yii2(but it was not just port - a lots of server-side things were changed... mostly it was fixes of design mistakes from Yii1 version)
