### ISSUE TITLE
Class 'Imagine\Imagick\Imagine' not found

### ISSUE THREAD

**Issue by amismailphp** [zxbodya/yii2-gallery-manager#22]
![gallery-error](https://cloud.githubusercontent.com/assets/9459819/12448690/7ebf77c8-bf80-11e5-95ed-f2cee99a57ff.png)

**Comment by zxbodya** [comment]
Strange... - looks like Imagine library is not installed.. 

Try to reinstall your composer dependencies.

**Comment by amismailphp** [comment]
Solved, Many thanks

**Comment by AlbertoMrFz** [comment]
i have same issue
