### ISSUE TITLE
 Exception: Invalid Parameter named "photo" updating the model

### ISSUE THREAD

**Issue by lidiexy** [zxbodya/yii2-gallery-manager#28]
Great extension! 
I'm doing a test with one of my Models (Dealer) to get the extension up and running. I just add one "image" field cause some errors, but when everything seems to be working, and the files were generated, also all "gallery_image" fields were populated. (I can see the image rendered in the "view" action) but the "update" action is through me an Invalid Parameter – yii\base\InvalidParamException.
.... backend\models\Dealer has no relation named "photos".

I was checking the GalleryManagerAction/changeData action... and there you have the parameter photo, so what kind of changes I need to do or any other ideas to fix this Exception.

Thanks

**Comment by zxbodya** [comment]
Hi, 
Can you upload your code related to gallery extension?

**Comment by lidiexy** [comment]
The Model and the Controller... let me know if you need something else...
[code-ex-gallery-extension.zip](https://github.com/zxbodya/yii2-gallery-manager/files/166316/code-ex-gallery-extension.zip)

**Comment by zxbodya** [comment]
I suspect it happens because of `use \mootensai\relation\RelationTrait` in you model.

Try to move gallery widget outside your form tag. (widget has some input fields in it, and it looks like those fields are not ignored when form is submitted)

**Comment by lidiexy** [comment]
Well, thanks. I tried other solution and is working right now. The _RelationTrait_ is working like a charm, but the problem was with the `Yii:$app->request->post()`. After using the _RelationTrait_ 
`$_POST != Yii::$app->request->post()`
