### ISSUE TITLE
Problem in create 

### ISSUE THREAD

**Issue by Sadykh** [zxbodya/yii2-gallery-manager#29]
Hello.

My english is very bad. I have next problem:
I create new page, after create I get next error:
rename(/var/www/rweb/www/web/files/product_gallery/,/var/www/rweb/www/web/files/product_gallery/11): Invalid argument
in /var/www/rweb/www/vendor/zxbodya/yii2-gallery-manager/GalleryBehavior.php line 159

Why? What i am doing not right? Please, help me.

**Comment by zxbodya** [comment]
It is strange - `afterUpdate` should not be triggered when saving record first time.

Here is a place in Yii source code, where it should be triggered:
https://github.com/yiisoft/yii2/blob/5c4e2d4372fc5932c821a2a490c61c9350fdb4fb/framework/db/BaseActiveRecord.php#L907

Probably you have some code that results in this strange behaviour. It is not in this exatension, at least it looks so.

**Comment by Sadykh** [comment]
Thank you, Bogdan Savluk.
Yes, of course. I found problem in my code. Sorry. Thank you!

**Comment by nelsonyrg** [comment]
HI thanks for sharing, i have the same issue with my app, an effectively i'm trying to put the gallery in a module/extension. as you find the problem, but how exactly i have to fix it. where i have to change the actions method  in the controller inside the module as indicates the installation instructions?

**Comment by kwazaro** [comment]
I've got the same problem. How to fix it? (PHP Warning - rename(...): Invalid argument . This happens when creating a model with attached galleryBehavior
