### ISSUE TITLE
502 ошибка при аплоаде

### ISSUE THREAD

**Issue by ekadesign** [zxbodya/yii2-gallery-manager#33]
при загрузке изображения с шаблоном advanced я получаю 502 ошибку. С чем это может быть связано ? Устанавливал из композера, из настроек сменил пути загрузки изображений. пробовал оставлять как есть, всё равно 502

**Comment by zxbodya** [comment]
может быть лимит для аплоада слишком маленький, попробуйте файлы меньше

или попробуйте увеличить лимит для аплоада (для nginx - `client_max_body_size 50M;`)

**Comment by ekadesign** [comment]
не помогло. При этом ещё отваливается апач, а nginx в логах пишет следующее:
2016/08/26 15:41:26 [error] 19500#8956: *2 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: backend.favor33.local, request: "POST /perfomances/galleryApi?type=perfomances&behaviorName=galleryBehavior&galleryId=1&action=ajaxUpload HTTP/1.1", upstream: "http://127.0.0.1:8080/perfomances/galleryApi?type=perfomances&behaviorName=galleryBehavior&galleryId=1&action=ajaxUpload", host: "backend.favor33.local", referrer: "http://backend.favor33.local/perfomances/update?id=1"

**Comment by ekadesign** [comment]
upd - Решилось сменой апача и nginx (openserver apache 2.2 + nginx 1.8) работают
Версия 2.4 + 1.9 Нет
