### ISSUE TITLE
Yii2 Gallery Manager store image database in same table "gallery_image", Can I separate table? Please help!!!

### ISSUE THREAD

**Issue by chomnan** [zxbodya/yii2-gallery-manager#34]
I really tried to migrate yii2-gallery-image extension for yii2 because it is what I need to build my own system, this extension look cool interface and easy to use. Until now I done integrate it to my application and uploaded successful but all images database store in same table. So could all of you help me to solved this?

**Comment by zxbodya** [comment]
It is intended to work this way…
I did not see any reason changing this, also it can be hard to change.

**Comment by chomnan** [comment]
Thanks for your replied.
Actually, I am working on medium project for client update to gallery page themselves and their are a lots of gallery sections to update like client stations, rate plan and other sections. So I want separate it to make sure the section go by under category on table that I migrate. However I worry in the future my app will working slow to filter image because all image gallery store in the same place. So it would be good if extension can set the condition to separate table. It's just the recommend only.

**Comment by chomnan** [comment]
Hi Zxbodya, No problem I can do it now. The Table is working separate now.
