### ISSUE TITLE
Viewer to select photos from the server

### ISSUE THREAD

**Issue by Resmedia** [zxbodya/yii2-gallery-manager#36]
Hello! Is it possible to do viewer and select photos from the server, because often, people upload the same photos, example in news.

**Comment by zxbodya** [comment]
No, - currently it is designed to have separate files for each gallery image, so even when adding possibility to select existing files from server - it still will copy them.

I think, to have possibility to properly reuse images already uploaded to server - you will need to almost rewrite it(however maybe you can reuse some front-end parts).
