### ISSUE TITLE
Can't upload pictures with size more than 2M

### ISSUE THREAD

**Issue by MaksimDzhangirov** [zxbodya/yii2-gallery-manager#40]
Good day! Can you help me?
I change settings in php.ini, but it didn't help.
upload_max_filesize = 20M, post_max_size = 20M

![1234](https://cloud.githubusercontent.com/assets/12369402/23397534/a1226342-fda1-11e6-98d7-ae8f86169a55.png)
![23](https://cloud.githubusercontent.com/assets/12369402/23397540/a398e1b4-fda1-11e6-8d58-a169509d3753.png)
![45](https://cloud.githubusercontent.com/assets/12369402/23397542/a64dc302-fda1-11e6-8b44-c979ffc78cab.png)
![56](https://cloud.githubusercontent.com/assets/12369402/23397546/ab3c8f06-fda1-11e6-83eb-3fd13ae95f7c.png)
![67](https://cloud.githubusercontent.com/assets/12369402/23397552/af9f17a8-fda1-11e6-9a4c-2313ad1d4c1d.png)
![78](https://cloud.githubusercontent.com/assets/12369402/23397554/b2113778-fda1-11e6-9f8e-98f1a8d52039.png)

**Comment by zxbodya** [comment]
You also need to adjust max request body size in your webserver configuration, for nginx it is `client_max_body_size`.

**Comment by MaksimDzhangirov** [comment]
Problem was in memory_limit. I changed memory_limit to 428M and its works.
