### ISSUE TITLE
How to access images without creating objects?

### ISSUE THREAD

**Issue by kwazaro** [zxbodya/yii2-gallery-manager#44]
How can I access or retrieve image related to model, if it is non-object, but array? For example, I have Product model with galleryBehavior. But because of memory limitations I access to it in array mode: 
```
$product = Product::find()->where(['id' => 325])->asArray()->one();
```
How can I get link for image, attached to this product? I know, that this extension creates folders for each model, naming them according to ID of model item. But there are some subfolders with another ID's (probably, with ID from database table of gallery_images) where images are located (original.jpg, preview.jpg etc.(.

**Comment by zxbodya** [comment]
It was not planned to be used un this way…

In general - you are right urls are created as following:

`<url from config>/<galleryId>/<imageId>/<version>.<extension>?<timeHash>=<crc32(image modification time)>`

`<galleryId>` is owner model primary keys concatenated using pkGlue('_' by default) parameter as separator.

`<imageId>` - `id` from `gallery_image` table, you can find related images using type specified in behavior config and ownerId as `galleryId` described above.

**Comment by kwazaro** [comment]
`<imageId>` - that's the problem. How can I get it from separate Product query result? I know product primary key (ID) value, I know resulting image filename (original.jpg), but I can't complete the file path, because I don't know `imageId`. The image file is located somewhere in `/images/product/325/???/original.jpg`. Should I have to create separate model for gallery_image database table and set relation with my Product model for joining the results in queries? Or maybe there is some simple solution?

**Comment by zxbodya** [comment]
Just query database directly, like here: https://github.com/zxbodya/yii2-gallery-manager/blob/master/GalleryBehavior.php#L171

**Comment by kwazaro** [comment]
Thanks.
