### ISSUE TITLE
Вынести все шаблоны блоков разметки в виджет для изменения.

### ISSUE THREAD

**Issue by bupy7** [zxbodya/yii2-gallery-manager#5]
Я так понял, что ты русский, поэтому как бы пишу так.

Можешь вынести все шаблоны HTML разметки из js файла в виджет для изменения? Я бы даже сказал, в идеале, достаточно, чтобы можно было изменять аттрибуты div, где класс .photo, .image-preview.

**Comment by zxbodya** [comment]
Не совсем, вообще-то я украинец. Общие вопросы тоже лучше писать на английском, многие кто захочет прочитать не знают русского.

---

Вообще проект делался в первую очередь как виджет для админки и особая кастомизация не планировалась.

Шаблоны сложновато выносить, и лучше оставить как есть чтобы не отломать чего ненароком... - там много логики завязано на структуре этих шаблонов и именах классов в них(если править то надо следить ничего ли не поломалось). 

Если возможно - лучше ограничится правкой стилей.

В принципе вынести шаблоны можно, но это надо делать или через какой-то шаблонизатор, или в опциях скрипта передавать js функции с шаблонами.

Но это тоже получится довольно неудобно для использования - часть шаблонов в js, часть в css... какие-то ресурсы надо подключать какие-то нет... В общем не сильно что-то поменяет в сравнении с вариантом сделать локальный форк и подправить под конкрентый проект.

**Comment by bupy7** [comment]
Тогда, как я писал ниже, достаточна только возможность править аттрибуты. Я не думаю, что вызовет много проблем конкатенация к существующим классам в блоках. Этого больше, чем достаточно.

**Comment by zxbodya** [comment]
не пойму, зачем править атрибуты этих блоков?
и как это должно выглядеть в настройках виджета?

**Comment by bupy7** [comment]
Например, добавить CSS классы Bootsrap. Как это выглядеть будет в виджете - на ваше усмотрение. Обычно обзывают свойства в стиле 

```php
public $<name>Options = [];
```

**Comment by zxbodya** [comment]
а почему просто не переопределить стили для этих блоков? также проще будет...

**Comment by bupy7** [comment]
class="col-md-3" - придется переопределять так же и media. Это очень геморно и не очень хорошее решение.

**Comment by dmitiyk** [comment]
Извиняюсь за некропостинг, но возник тот же вопрос, хочется сделать дополнительный атрибут к изображению помимо название и описания, для перестройки логики надо просто переопределить пару методов, а вот что делать с шаблонами не пойму, не хочется полностью использовать свой js файл, как лучше поступить в данному случае?

**Comment by zxbodya** [comment]
пока, по-другому никак.. тот JS что там сейчас не особо расширяем.
