### ISSUE TITLE
Unexpected rights with createFolder

### ISSUE THREAD

**Issue by bscheshirwork** [zxbodya/yii2-gallery-manager#61]
https://github.com/zxbodya/yii2-gallery-manager/blob/db899b2c1225c642e3b97ac8c3a95edc1bac171a/GalleryBehavior.php#L278-L288

This command depends of umask(); For example if umask(); return 18 the folders created chmod 0755 instead passed 0777;

I try to use FileHelper for update this:
```php
    private function createFolders($filePath)
    {
        return FileHelper::createDirectory(FileHelper::normalizePath($filePath), 0777);
    }
```

**Comment by zxbodya** [comment]
it was migrated from Yii 1.x :) so that is why FileHelper was not used…

but with it looks much better.
